name: Telegram Custom Upload

on:
  workflow_dispatch:
    inputs:
      API_ID:
        description: 'Telegram API ID'
        required: true
        type: number
      API_HASH:
        description: 'Telegram API HASH'
        required: true
        type: string
      BOT_TOKEN:
        description: 'Bot Token(Sender)'
        required: true
        type: string
      CHAT_ID:
        description: 'Chat ID(Receiver)'
        required: true
        type: number

jobs:
  tg-upload:
    uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
    secrets:
      TELEGRAM_API_ID: ${{ inputs.API_ID }}
      TELEGRAM_API_HASH: ${{ inputs.API_HASH }}
      TELEGRAM_BOT_TOKEN: ${{ inputs.BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ inputs.CHAT_ID }}
